name: build-publish-skin
description: Sets up the environment for the building the skin, runs the build command and releases the skin through semantic release
inputs:
  gh-token:
    description: The GitHub token to release the skin
    required: true
runs:
  using: composite
  steps:
    - id: setup-node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - id: setup-environment
      shell: bash
      run: |
        sudo apt-get install -y jq moreutils
        npm i -g delta-skin-generator
    - name: release-skin
      uses: cycjimmy/semantic-release-action@v4
      with:
        extends: delta-skin-generator-release-config
        extra_plugins: |
          @semantic-release/exec
          delta-skin-generator-release-config
      env:
        GITHUB_TOKEN: ${{ inputs.gh-token }}